% Solve a Clustering Problem with a Self-Organizing Map
% Script generated by NCTOOL
% Created Fri Aug 16 14:39:57 IST 2013
%
% This script assumes these variables are defined:
%
%   ftraindb - input data.

inputs = ftraindb';

% Create a Self-Organizing Map
dimension1 = 10;
dimension2 = 10;
net = selforgmap([dimension1 dimension2]);

% Train the Network
[net,tr] = train(net,inputs);

% Test the Network1=
outputs = net(inputs);

% View the Network
view(net)
c1='C:\SPOORTHI_LAB\PROJ\PROJ\';

y1=spoofun(c1,'watermelon2.jpg');
display(y1)
y2=sim(net,y1');
%%y2=ind2vec(y2);
y3=strcat('FRUIT CLASS--->',num2str(y2));
display(y3)
% Plots
% Uncomment these lines to enable various plots.
%figure, plotsomtop(net)
%figure, plotsomnc(net)
%figure, plotsomnd(net)
%figure, plotsomplanes(net)
%figure, plotsomhits(net,inputs)
%figure, plotsompos(net,inputs)
